### ISSUE TITLE
Blog page is broken

### ISSUE THREAD

**Issue by sid-r-singh** [pirsch-analytics/blog#5]
https://pirsch.io/blog seems to be broken

![image](https://user-images.githubusercontent.com/68782815/146984619-1b59f2d5-21b4-40f4-b73a-43e4cc9f4d2c.png)

**Comment by Kugelschieber** [comment]
Hi Sid, thanks for pointing it out! We are working on a "fix" (new blog integrated into our website) right now :)

**Comment by Kugelschieber** [comment]
This will still use this repo btw., but we generate the content ourselves without using Hugo.

**Comment by Kugelschieber** [comment]
Fixed!
